[package]
name = "ic-file-uploader"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"
description = "A utility for uploading files to Internet Computer canisters."
license = "MIT OR Apache-2.0"

[dependencies]
tempfile = "3.9.0"

[[bin]]
name = "ic-file-uploader"
path = "src/main.rs"